// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFilePath(arg1) {
  return window['go']['main']['App']['OpenFilePath'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
