// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFilePath(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;
